<?php
/**
 * @file
 * Main file for the Panels Pane Report module.
 */

/**
 * Implements hook_permission().
 */
function panels_pane_report_permission() {
  $permissions['access panels pane report'] = array(
    'title' => t('Access Panels Pane Report'),
    'description' => t('Provides access to panels pane report'),
  );

  $permissions['generate panels pane report'] = array(
    'title' => t('Generate Panels Pane Report'),
    'description' => t('Allows a user to regenerated the panels pane report'),
  );

  return $permissions;
}

/**
 * Implements hook_views_api().
 */
function panels_pane_report_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'panels_pane_report'),
  );
}

/**
 * Implements hook_cronapi().
 */
function panels_pane_report_cronapi() {
  $items = array();

  // TODO: Setup cron in admin panel.

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function panels_pane_report_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  $id = str_replace('-', '_', $form['#id']);
  $fn = __FUNCTION__ . '__' . $id;
  if (function_exists($fn)) {
    $fn($form, $form_state, $form_id);
  }
}

/**
 * Adds a 'Regenerate Report' button to the views form.
 */
function panels_pane_report_form_views_exposed_form_alter__views_exposed_form_panels_pane_report_page(&$form, &$form_state, $form_id) {
  if (user_access('generate panels pane report')) {
    $form['submit']['#value'] = t('Search');
    $form['regenerate_report'] = array(
      '#type' => 'submit',
      '#value' => t('Regenerate Report'),
      '#submit' => array_merge(array('panels_pane_report_run'), $form['#submit']),
    );
  }
}

/**
 * Callback to run the panels pane report.
 */
function panels_pane_report_run($form, &$form_state) {
  // TODO: Allow cron access here.
  if (user_access('generate panels pane report')) {
    PanelsPaneReport::runReport();
    cache_clear_all('panels_pane_report:', 'cache_views_data', TRUE);
  }
}
